#!/bin/bash
set -ex

CLIENTNAME="$1"


# Generate Client Certificates
docker run --volumes-from openvpn-data --rm -it kylemanna/openvpn easyrsa build-client-full $CLIENTNAME nopass

echo "********************************"
echo "#Copy this to $CLIENTNAME.ovpn securly on client machine"
docker run --volumes-from openvpn-data --rm kylemanna/openvpn ovpn_getclient $CLIENTNAME

