#!/bin/bash 
# https://www.digitalocean.com/community/tutorials/how-to-run-openvpn-in-a-docker-container-on-ubuntu-14-04
# https://github.com/kylemanna/docker-openvpn
set -ex

OVPN_DATA="openvpn-data" 
IP=$(curl -s https://api.ipify.org)

docker rm -fv $OVPN_DATA || true
docker run --name $OVPN_DATA -v /etc/openvpn busybox

docker run --volumes-from $OVPN_DATA --rm kylemanna/openvpn ovpn_genconfig -u udp://$IP:1194

# Generate the EasyRSA PKI certificate authority.
docker run --volumes-from $OVPN_DATA --rm -it kylemanna/openvpn ovpn_initpki

cp service.conf /etc/systemd/system/openvpn-docker.conf

service docker-openvpn restart
